export const AuthActionTypes = {
  LOGIN_USER_BY_MAIL_START: "LOGIN_USER_BY_MAIL_START",
  LOGIN_USER_BY_MAIL_SUCCESS: "LOGIN_USER_BY_MAIL_SUCCESS",
  LOGIN_USER_BY_MAIL_FAIL: "LOGIN_USER_BY_MAIL_FAIL",
};
